{% set name = "neptune-xgboost" %}
{% set version = "0.9.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neptune-ai/{{ name }}/archive/{{ version }}.tar.gz
  sha256: ed1a42ebd8e82d7c80b216eb4cb1657e1ff6556ec7ac078d9a5cd9d7277983c7

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - neptune-client >=0.9
    - python >=3.6
    - xgboost >=1.3.0

test:
  imports:
    - neptune_xgboost
    - neptune_xgboost.impl

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client integration with XGBoost
  doc_url: https://github.com/neptune-ai/neptune-xgboost/blob/master/README.md
  dev_url: https://github.com/neptune-ai/neptune-xgboost

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - PiotrJander
    - shnela
    - pkasprzyk
